# Generated by Django 5.2 on 2025-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0002_datastream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='datastream',
            unique_together={('room', 'user')},
        ),
    ]
