# Generated by Django 5.2 on 2025-04-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0004_datastream_meeting_roo_room_id_22676d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='data',
        ),
        migrations.AddField(
            model_name='datastream',
            name='focus_data',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datastream',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
            preserve_default=False,
        ),
    ]
